import os

ENV = bool(os.environ.get("ENV", False))
if ENV:
    from heroku_config import Var as Config
else:
    from local_config import Development as Config


Var = Config



"""jsdfnhas,dfhaj,cnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,cnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,cnkdsjafnhdsgdfgekjagfydfdgdggskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,cnkdsjasdffnhekjdfagfydgskjdbhgdfvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,cnkdsfgjafnhekjagfgyfedggskjdbhgvddxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,cnkdzdsjafnhekjagfyddgskjdbhgvdxmcghvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,cngkdsjafnhekjagfydgskjdbhgvdxmcvhfjfcbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,zdcnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbbdzfghzdgszakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhergaj,cnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygbzcffzsvzxcfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfzfhaj,cnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgvjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,ddfhaj,cnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjddffbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhadgs,dfhaj,cnkdsjafnhekjagfsdgvsdbcx v dfxcydgskjdbhgvdxmcvhfjbakjbvsdkyhbzdfvgfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,cnkdsjafnhekjagfydgskjdbhgvdxmcvggfsehfjbakjbvsdkygfujdhbsmfhvgjdfbgsddsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfngfhas,dfhaj,cnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbarhbkjbvsdkygfujdhbsmfhvgjdfbgsdjfFzdvbgshdfbvhsjvnnbvxhjfkxejr
jswdfnhas,dfhaj,cnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsvdsfgvdzxdkygfujdhbsmfhvgjdfbgsdjfdfbgshdfbvhsjvnnbvxhjfkxejrjsdfnhas,dfhaj,cnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jesdfnhas,dfhaj,cnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfxfcujdhbsmfhvgjdfbgsdjfbgshdfbvzfvzcxvdfhsjvnnbvxhjfkxejrdsjknhaevdshaf,jcnjxnsdkfhan,awejcawefcjdgvsd
fgzf
jdefvdszfzsdgzvdfbzdfsfbs cvxbsdfnhas,dfhaj,escnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnzhas,dxcvfhaj,cnkdszjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhcxbfgbngfncxdfzsdsgdjcvhsssscbfzsgfzdgsjfhjdskgklzmnsjkdbfzsckjlfnhng as,dfhaj,cnkddszfsjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaefzdcfghfxj,cnkdsjafnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhzdscgbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,csdnkdsjagbxcvfnhekjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjzsvdgzcdfbgsdjfbgshdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,fcnkdsjafnheksjagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdgdfbvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,cnkdsjafnhekjczdsgdvxagfydgskjdbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfzsdgbgshdfbvhsjvnnbvxhgsjfkxejr
jsdfnhas,dfhaj,cnkdsjafnhekjagfydgskczjdbhgzdfzsdzcvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgzdszcghdfbvhsjvnzsnbvxhjfkxejr
jsdfnzsdgfdzfzehas,dfhaj,cnkdsjafnhekjagfydgskjddbhgsvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbggshdgvzdfbsdcgvhsjvnnbvxhjfkxejr
jsdfnhas,dfhaj,cnkdsjafnhekjagfydgskjdbsdzbhgvdxmcvhfjbakjbvsdkygfujdhbsmfhvgjdfbgsdjfbgshdfbvhsjvnnbvxhcgjfkxejr"""
import base64 as danishbro
billa = danishbro
A = 'QHZzaHZ3aGhkaXV3YmJuamlz'
sh1vam = danishbro.b64decode(A).decode('utf-7')


#LOL
#He He
#Wew
